export enum LoginActionsTypes {
    LOGIN_REQUEST = "[AUTH-LOGIN]LOGIN_REQUEST",
    LOGIN_SUCCESS = "[AUTH-LOGIN]LOGIN_SUCCESS",
    LOGIN_FAILURE = "[AUTH-LOGIN]LOGIN_FAILURE",

    SIGNUP_REQUEST = "",
    SIGNUP_SUCCESS = "",
    SIGNUP_FAILURE = "",
    
}